# Generated by Django 3.2.8 on 2021-10-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='name',
            field=models.CharField(help_text='接口名称', max_length=30, null=True, unique=True, verbose_name='接口名称'),
        ),
    ]
