# Generated by Django 3.2.8 on 2021-10-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_project'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='tb_projects',
        ),
    ]
